name: Build documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Pandoc
      run: sudo apt-get install pandoc texlive-latex-base
    - name: Convert Markdown to PDF
      run: pandoc -o documentation.pdf documentation.md
    - name: Convert Markdown to HTML
      run: pandoc -o documentation.html documentation.md
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
